<?xml version="1.0"?>
<robot>

<!--
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
      iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
      izz="${m*r*r/2}"
    />
  </macro>

  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
      iyy="${m*(x*x+z*z)/12}" iyz = "0"
      izz="${m*(x*x+z*z)/12}"
    />
  </macro>

  <macro name="sphere_inertia" params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
      iyy="${2*m*r*r/5}" iyz = "0"
      izz="${2*m*r*r/5}"
    />
  </macro>



-->




  <macro name="wheel" params="lr tY">

    <link name="${lr}_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <mass value="${wheelMass}"/>
        <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
      </inertial>
    </link>

    <gazebo reference="${lr}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
    </gazebo>


    <joint name="${lr}_wheel_hinge" type="continuous">
      <parent link="chassis"/>
      <child link="${lr}_wheel"/>
    <origin xyz="${-wheelPos+chassisLength/2} ${tY*wheelWidth/2+tY*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="10000" velocity="10000"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>


    <transmission name="${lr}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_hinge">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}Motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>10</mechanicalReduction>
      </actuator>
    </transmission>

  </macro>

  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/snake</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <material name="Blue">
    <color rgba="0.2 0.1 0.8 1.0"/>
  </material>
  <material name="Green">
    <color rgba="0.22 0.32 0.14 1.0"/>
  </material>

	<!-- attach the base_link to world -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

	<link name="base_link">
		<visual>
			<origin
				xyz="0. 0. 0."
				rpy="1.57079632679 0 1.57079632679"
			/>
			<geometry>
				<mesh
					filename="package://snake_robot/snake_description/meshes/servo.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="Blue"/>
		</visual>
		
		<!-- in gazebo, there has to be a mass and an inertia for each link -->
		<inertial>
      <origin xyz="0 0 0.036" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
	</link>

	<joint name="joint1" type="continuous">
		<origin
			xyz="0. 0. 0."
			rpy="0. 0. 0."
		/>
		<parent link="base_link"/>
		<child link="link2"/>
		<safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.5" soft_upper_limit="1.5"/>
		<limit effort="0.01" lower="-1" upper="1" velocity="0.5"/>
		<dynamics damping="0.7"/>
	</joint>

	<link name="link2">
		<visual>
			<origin
				xyz="0. 0. 0.072"
				rpy="1.57079632679 0 0."
			/>
			<geometry>
				<mesh
					filename="package://snake_robot/snake_description/meshes/servo.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="Green"/>
		</visual>

		<inertial>
	    <origin xyz="0 0 0.036" rpy="0 0 0"/>
	    <mass value="1"/>
	    <inertia
		  ixx="0.1" ixy="0.0" ixz="0.0"
		  iyy="0.1" iyz="0.0"
		  izz="0.1"/>
	    </inertial>
	</link>

	<joint name="joint2" type="continuous">
		<origin
			xyz="0. 0. 0.072"
			rpy="0. 0. 1.57079632679"
		/>
		<parent link="link2"/>
		<child link="link3"/>
		<safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.5" soft_upper_limit="1.5"/>
		<limit effort="0.01" lower="-1" upper="1" velocity="0.5"/>
		<dynamics damping="0.7"/>
	</joint>

	<link name="link3">
		<visual>
			<origin
				xyz="0. 0. 0.072"
				rpy="1.57079632679 0 1.57079632679"
			/>
			<geometry>
				<mesh
					filename="package://snake_robot/snake_description/meshes/servo.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="Green"/>
		</visual>
		
		<inertial>
	    <origin xyz="0 0 0.036" rpy="0 0 0"/>
	    <mass value="1"/>
	    <inertia
		  ixx="0.1" ixy="0.0" ixz="0.0"
		  iyy="0.1" iyz="0.0"
		  izz="0.1"/>
	  </inertial>
	</link>

<transmission name="trans1">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint1">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </joint>
  <actuator name="servo1">
    <mechanicalReduction>1</mechanicalReduction>
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </actuator>
</transmission>

<transmission name="trans2">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint2">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </joint>
  <actuator name="servo2">
    <mechanicalReduction>1</mechanicalReduction>
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </actuator>
</transmission>





</robot>
